import { Organization, PermissionLevel } from '@/gql/graphql';

export const availableMemberPermissionGroups: Organization['availableMemberPermissionGroups'] = [
  {
    __typename: 'PermissionGroup',
    id: 'organization',
    title: 'Organization',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: true,
        id: 'organization:describe',
        dependsOnId: null,
        description: 'Member can see the organization. Permission can not be modified.',
        level: PermissionLevel.Organization,
        title: 'View organization',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'support:manageTickets',
        dependsOnId: null,
        description: 'Member can access, create and reply to support tickets.',
        level: PermissionLevel.Organization,
        title: 'Access support tickets',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'organization:modifySlug',
        dependsOnId: null,
        description: 'Member can modify the organization slug.',
        level: PermissionLevel.Organization,
        title: 'Update organization slug',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'auditLog:export',
        dependsOnId: null,
        description: 'Member can access and export the audit log.',
        level: PermissionLevel.Organization,
        title: 'Export audit log',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'organization:delete',
        dependsOnId: null,
        description: 'Member can delete the Organization.',
        level: PermissionLevel.Organization,
        title: 'Delete organization',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'members',
    title: 'Members',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'member:describe',
        dependsOnId: null,
        description: 'Member can access the organization member overview.',
        level: PermissionLevel.Organization,
        title: 'View members',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'member:modify',
        dependsOnId: 'member:describe',
        description: 'Member can assign roles to users.',
        level: PermissionLevel.Organization,
        title: 'Assign member role',
        warning:
          'Granting a role the ability to assign roles enables it to elevate its own permissions.',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'billing',
    title: 'Billing',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'billing:describe',
        dependsOnId: null,
        description: 'Member can view the billing information.',
        level: PermissionLevel.Organization,
        title: 'View billing',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'billing:update',
        dependsOnId: 'billing:describe',
        description: 'Member can change the organization plan.',
        level: PermissionLevel.Organization,
        title: 'Update billing',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'oidc',
    title: 'OpenID Connect',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'oidc:modify',
        dependsOnId: null,
        description: 'Member can connect, modify, and remove an OIDC provider to the connection.',
        level: PermissionLevel.Organization,
        title: 'Manage OpenID Connect integration',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'github',
    title: 'GitHub Integration',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'gitHubIntegration:modify',
        dependsOnId: null,
        description:
          'Member can connect, modify, and remove access for the GitHub integration and repository access.',
        level: PermissionLevel.Organization,
        title: 'Manage GitHub integration',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'slack',
    title: 'Slack Integration',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'slackIntegration:modify',
        dependsOnId: null,
        description:
          'Member can connect, modify, and remove access for the Slack integration and repository access.',
        level: PermissionLevel.Organization,
        title: 'Manage Slack integration',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'project',
    title: 'Project',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'project:create',
        dependsOnId: null,
        description: 'Member can create new projects.',
        level: PermissionLevel.Organization,
        title: 'Create project',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'project:describe',
        dependsOnId: null,
        description: 'Member can access the specified projects.',
        level: PermissionLevel.Project,
        title: 'View project',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'project:delete',
        dependsOnId: 'project:describe',
        description: 'Member can access the specified projects.',
        level: PermissionLevel.Project,
        title: 'Delete project',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'project:modifySettings',
        dependsOnId: 'project:describe',
        description: 'Member can access the specified projects.',
        level: PermissionLevel.Project,
        title: 'Modify Settings',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'schema-linting',
    title: 'Schema Linting',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'schemaLinting:modifyOrganizationRules',
        dependsOnId: null,
        description: 'Member can view and modify the organization schema linting rules.',
        level: PermissionLevel.Organization,
        title: 'Manage organization level schema linting',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'schemaLinting:modifyProjectRules',
        dependsOnId: 'project:describe',
        description: 'Member can view and modify the projects schema linting rules.',
        level: PermissionLevel.Project,
        title: 'Manage project level schema linting',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'target',
    title: 'Target',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'target:create',
        dependsOnId: 'project:describe',
        description: 'Member can create new projects.',
        level: PermissionLevel.Project,
        title: 'Create target',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'target:delete',
        dependsOnId: 'project:describe',
        description: 'Member can access the specified projects.',
        level: PermissionLevel.Target,
        title: 'Delete target',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'target:modifySettings',
        dependsOnId: 'project:describe',
        description: 'Member can access the specified projects.',
        level: PermissionLevel.Target,
        title: 'Modify settings',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'alert:modify',
        dependsOnId: 'project:describe',
        description: 'Can create alerts for schema versions.',
        level: PermissionLevel.Project,
        title: 'Modify alerts',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'targetAccessToken:modify',
        dependsOnId: 'project:describe',
        description: 'Allow managing access tokens for CLI and Usage Reporting.',
        level: PermissionLevel.Target,
        title: 'Manage registry access tokens',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'cdnAccessToken:modify',
        dependsOnId: 'project:describe',
        description: 'Allow managing access tokens for the CDN.',
        level: PermissionLevel.Target,
        title: 'Manage CDN access tokens',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'laboratory',
    title: 'Laboratory',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'laboratory:describe',
        dependsOnId: 'project:describe',
        description: 'Member can access the laboratory, view and execute GraphQL documents.',
        level: PermissionLevel.Target,
        title: 'View laboratory',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'laboratory:modify',
        dependsOnId: 'laboratory:describe',
        description:
          'Member can create, delete and update collections and documents in the laboratory.',
        level: PermissionLevel.Target,
        title: 'Modify laboratory',
      },
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'laboratory:modifyPreflightScript',
        dependsOnId: 'laboratory:describe',
        description: 'Member can update the laboratory preflight script.',
        level: PermissionLevel.Target,
        title: 'Modify the laboratory preflight script',
      },
    ],
  },
  {
    __typename: 'PermissionGroup',
    id: 'schema-checks',
    title: 'Schema Checks',
    permissions: [
      {
        __typename: 'Permission',
        isReadOnly: false,
        id: 'schemaCheck:approve',
        dependsOnId: 'project:describe',
        description: 'Member can approve failed schema checks.',
        level: PermissionLevel.Service,
        title: 'Approve schema check',
      },
    ],
  },
];
